name: Lint MarkDown

on: [push]

jobs:
    markdownlint:
        runs-on: ubuntu-latest
        steps:
            - uses: "articulate/actions-markdownlint@v1"
              with:
                  github_token: "${{ secrets.GITHUB_TOKEN }}"